# Generated by Django 5.1.5 on 2025-01-25 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_rename_post_survey_postquestion_postanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postquestion',
            old_name='post',
            new_name='survey',
        ),
        migrations.RemoveField(
            model_name='postanswer',
            name='is_right',
        ),
    ]
