# Generated by Django 5.1.5 on 2025-01-25 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_rename_post_postquestion_survey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postquestion',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
    ]
