# Generated by Django 5.1.5 on 2025-01-27 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_postquestion_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.postquestion'),
        ),
        migrations.AlterField(
            model_name='postquestion',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.survey'),
        ),
    ]
